stages:
  prepare_data:
    cmd: python src/00_prepare.py --config src/config.yaml
    deps:
      - src/00_prepare.py
      - src/config.yaml
    outs:
      - data/input/dummy_data.npy

  train:
    cmd: PYTHONPATH=src python src/01_train.py --config src/config.yaml
    deps:
      - src/01_train.py
      - src/models.py
      - data/processed_data/
      - src/config.yaml
    outs:
      - models/model_v2.pt
      - src/preprocess.py
      - src/postprocess.py

  evaluate:
    cmd: PYTHONPATH=src python src/02_evaluate.py --config src/config.yaml
    deps:
      - src/02_evaluate.py
      - models/model_v2.pt
    metrics:
      - metrics/evaluation.json
