stages:
  prepare:
    cmd: python src/00_prepare.py --config src/config.yaml
    deps:
      - src/00_prepare.py
      - src/config.yaml
    outs:
      - data/processed_data/

  train:
    cmd: python src/01_train.py --config src/config.yaml
    deps:
      - src/01_train.py
      - src/models.py  # Updated model location
      - data/processed_data/
      - src/config.yaml
    outs:
      - models/model.pt
      - src/preprocess.py
      - src/postprocess.py

  evaluate:
    cmd: python src/02_evaluate.py --config src/config.yaml
    deps:
      - src/02_evaluate.py
      - src/models.py  # Updated model location
      - models/model.pt
      - src/config.yaml
    metrics:
      - metrics/evaluation.json
