stages:
  prepare:
    cmd: python src/00_prepare.py --config src/config.yaml
    deps:
      - src/00_prepare.py
      - src/config.yaml
    outs:
      - data/processed_data/

  train:
    cmd: PYTHONPATH=src python src/01_train.py --config src/config.yaml
    deps:
      - src/01_train.py
      - src/models.py
      - data/processed_data/
      - src/config.yaml
    outs:
      - models/model_v3.pt  # New model file for version 3.0
      - src/preprocess.py
      - src/postprocess.py

  evaluate:
    cmd: PYTHONPATH=src python src/02_evaluate.py --config src/config.yaml
    deps:
      - src/02_evaluate.py
      - src/models.py
      - models/model_v3.pt  # New model file for version 3.0
      - src/config.yaml
    metrics:
      - metrics/evaluation.json
