output: "data/input/dummy_data.npy"  # The output path where the prepared data will be saved

# You can add additional configurations here if needed for training or evaluation
train:
  epochs: 10
  learning_rate: 0.001

evaluate:
  threshold: 0.7
